dataset_name: jordiclive/uspto2
model_name_or_path: "EleutherAI/pythia-70m-deduped"
output_dir: "layer9"
training_layers: "4,5"
per_device_train_batch_size: 8
per_device_eval_batch_size: 1
preprocessing_num_workers: 32
learning_rate: 1e-4
block_size: 9000
num_train_epochs: 1
gradient_accumulation_steps: 1
do_train: true
do_eval: true
evaluation_strategy: "steps"
save_total_limit: 2
max_grad_norm: 2.0
save_steps: 1
eval_steps: 1
max_steps: 1
overwrite_output_dir: true
logging_steps: 20
wandb_entity: "ontocord"
wandb_project: "jordi_testing"